{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "openproject.fullname" . }}-assets
  labels:
    app: {{ template "openproject.fullname" . }}
    chart: {{ template "openproject.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.assetsSize | quote }}
  {{ include "openproject.storageClass" . }}

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "openproject.fullname" . }}-pgdata
  labels:
    app: {{ template "openproject.fullname" . }}
    chart: {{ template "openproject.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.pgdataSize | quote }}
  {{ include "openproject.storageClass" . }}
{{- end }}
