{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "openproject.serviceAccountName" . }}
  labels:
{{ include "openproject.labels" . | indent 4 }}
{{- end -}}
