apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "squid.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "squid.name" . }}
    helm.sh/chart: {{ include "squid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "squid.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "squid.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: squid
              containerPort: 3128
              protocol: TCP
          volumeMounts:
            - mountPath: /var/spool/squid
              name: squid-cache
            - mountPath: /etc/squid/squid.conf
              subPath: squid.conf
              name: {{ template "squid.fullname" . }}-conf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: squid-cache
          emptyDir: {}
        - name: {{ template "squid.fullname" . }}-conf
          configMap:
            name: {{ template "squid.fullname" . }}-conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
